# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3pAPuS0d3d1MRMM5GLySsP6VXvvJBQt
"""

import torch
import torchvision.datasets as datasets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim

# Petite fonction pour corriger l'orientation des images EMNIST (bug officiel de la lib)
# Pour les tourner de 90°
def fix_emnist(image):
    return transforms.functional.rotate(transforms.functional.hflip(image), 90)


# 1. Transformations pour l'ENTRAÎNEMENT (avec Data Augmentation)
train_transform = transforms.Compose([
    transforms.Lambda(fix_emnist), # Corrige le sens des chiffres EMNIST
    transforms.RandomRotation(degrees=10), # Légère rotation (Personne n'ecrit parfaitement droit)
    transforms.RandomAffine(degrees=0, translate=(0.1, 0.1)), # Légéro déplacement (translation)
    transforms.ToTensor(), # Convertir l'image en tenseur Mathématique
    transforms.Normalize((0.1307,), (0.3081,)) # Normalisation standard (moyenne/écart-type MNIST/EMNIST)
])

# 2. Transformations pour le TEST / EVAL (Sans pivoter ou decalager legeremment l'image
test_transform = transforms.Compose([
    transforms.Lambda(fix_emnist), # Corrige aussi le sens pour les tests
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,)) # Même normalisation obligatoire !
])


# Chargement des datasets avec les bonnes transformations
train_data = datasets.EMNIST(
    root='./data',
    split='digits',
    train=True,
    download=True, #Pour télécharger le modèle sur internet
    transform=train_transform
)

test_data = datasets.EMNIST(
    root='./data',
    split='digits',
    train=False,
    download=True,
    transform=test_transform
)

# DataLoader : regroupe les images par paquet de 64
train_loader = DataLoader(train_data, batch_size=64, shuffle=True) # on mélange (uniquement pour les données d'entrainement)
test_loader = DataLoader(test_data, batch_size=64, shuffle=False)



# 3. Transformations pour les données personnelles
perso_transform = transforms.Compose([
    transforms.Grayscale(num_output_channels=1), # Forcer en Noir & Blanc
    transforms.Resize((28, 28)), # Standardiser la taille pour le modèle
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,)) # Conserver la normalisation EMNIST
])

# Chargement depuis tes 10 dossiers (0 à 9)
perso_data = datasets.ImageFolder(
    root='./chemin_vers_donnees_persos',
    transform=perso_transform
)

# DataLoader pour le fine-tuning ou l'évaluation
perso_loader = DataLoader(perso_data, batch_size=32, shuffle=False)

# Choisi le bon "device" (GPU si dispo, sinon CPU)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Utilisation du device : {device}")

# Pour l'instant, si tu n'as pas encore le modèle de P2,
# tu pourras y brancher ton modèle ici : model = TonModeleViT().to(device)

# Fonction de perte pour la classification (0 à 9)

# Pour sanctionner les ereurs
criterion = nn.CrossEntropyLoss()



# model = LeModeleViTDeP2().to(device)
#optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)

# Retourne running_loss / len(dataloader), qui indique si le modèle s'améliore
def train_one_epoch(model, dataloader, criterion, optimizer, device):

    model.train() # Mode entraînement (active le dropout, etc.)
    running_loss = 0.0

    for images, labels in dataloader:
        # 1. Envoyer les données sur le GPU ou CPU
        images, labels = images.to(device), labels.to(device)

        # 2. Remise à zéro des gradients
        optimizer.zero_grad()

        # 3. Forward pass (prédictions du modèle)
        outputs = model(images)

        # 4. Calcul de la perte (loss)
        loss = criterion(outputs, labels)

        # 5. Backpropagation (calcul des gradients)
        loss.backward()

        # 6. Ajutes les poids du modèle
        optimizer.step()

        running_loss += loss.item()

    return running_loss / len(dataloader)

def evaluate_model(model, dataloader, criterion, device):
    model.eval() # Désactive les comportements spécifiques à l'entraînement (ex: dropout)
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad(): # Désactive le calcul des gradients pour accélérer
        for images, labels in dataloader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)
            running_loss += loss.item()

            # Calcul de la précision
            # Predicted = index de ce score
            _, predicted = torch.max(outputs.data, 1) # vecteur de 10 scores (un pour chaque chiffre de 0 à 9)
            total += labels.size(0)

            # Compare les prédictions de l'IA avec la réalité
            correct += (predicted == labels).sum().item()

    accuracy = 100 * correct / total # Transforme le nombre de bonnes réponses en pourcentage
    return running_loss / len(dataloader), accuracy

#Modele va réviser la totalité du dataset 5 fois
epochs = 5



print("Début de l'entraînement...")
for epoch in range(epochs):
    # Entraînement
    train_loss = train_one_epoch(model, train_loader, criterion, optimizer, device)

    # Évaluation
    val_loss, val_acc = evaluate_model(model, test_loader, criterion, device)

    #Logiquement, train_loss et val_loss doivent diminuer progressivement
    print(f"Epoch {epoch+1}/{epochs} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Val Accuracy: {val_acc:.2f}%")

print("Entraînement terminé !")