# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3pAPuS0d3d1MRMM5GLySsP6VXvvJBQt
"""
import sys
import os


sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import torch
import torchvision.datasets as datasets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim
import numpy as np
from model.cnn import CNN
from torch.utils.data import Subset
import matplotlib.pyplot as plt

np.random.seed(42)

# Petite fonction pour corriger l'orientation des images EMNIST (bug officiel de la lib)
# Pour les tourner de 90°
def fix_emnist(image):
    return transforms.functional.rotate(transforms.functional.hflip(image), 90)


# 1. Transformations pour l'ENTRAÎNEMENT (avec Data Augmentation)
train_transform = transforms.Compose([
    transforms.Lambda(fix_emnist), # Corrige le sens des chiffres EMNIST
    transforms.RandomRotation(degrees=10), # Légère rotation (Personne n'ecrit parfaitement droit)
    transforms.RandomAffine(degrees=0, translate=(0.1, 0.1)), # Légéro déplacement (translation)
    transforms.ToTensor(), # Convertir l'image en tenseur Mathématique
    transforms.Normalize((0.1307,), (0.3081,)) # Normalisation standard (moyenne/écart-type MNIST/EMNIST)
])

# 2. Transformations pour le TEST / EVAL (Sans pivoter ou decalager legeremment l'image
test_transform = transforms.Compose([
    transforms.Lambda(fix_emnist), # Corrige aussi le sens pour les tests
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,)) # Même normalisation obligatoire !
])


# Chargement des datasets avec les bonnes transformations
train_data = datasets.EMNIST(
    root='./data',
    split='digits',
    train=True,
    download=True, #Pour télécharger le modèle sur internet
    transform=train_transform
)

test_data = datasets.EMNIST(
    root='./data',
    split='digits',
    train=False,
    download=True,
    transform=test_transform
)


train_subset = Subset(train_data, range(10000))
test_subset = Subset(test_data, range(2000))

# DataLoader : regroupe les images par paquet de 64
# DataLoader basés sur ces sous-ensembles minuscules
train_loader = DataLoader(train_subset, batch_size=64, shuffle=True, num_workers=0)
test_loader = DataLoader(test_subset, batch_size=64, shuffle=False, num_workers=0)

#train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
#test_loader = DataLoader(test_data, batch_size=64, shuffle=False)



# 3. Transformations pour les données personnelles
# 3. Transformations pour les données personnelles
# 3. Transformations pour les données personnelles
# 3. Transformations pour les données personnelles (Version Agressive)
perso_transform = transforms.Compose([
    transforms.Grayscale(num_output_channels=1),
    transforms.RandomRotation(degrees=10, fill=255), 
    # NOUVEAU : scale=(0.85, 1.15) fait grossir ou rétrécir le chiffre de 15% aléatoirement
    transforms.RandomAffine(degrees=0, translate=(0.1, 0.1), scale=(0.85, 1.15), fill=255), 
    transforms.Resize((28, 28)),
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

# Chargement depuis tes 10 dossiers (0 à 9)
perso_data = datasets.ImageFolder(
    root='./dataset_perso/dataset_augmente',
    transform=perso_transform
)

# DataLoader pour le fine-tuning ou l'évaluation
perso_loader = DataLoader(perso_data, batch_size=32, shuffle=True, num_workers=0)

# Initialisation du modèle fait maison (NumPy)
model = CNN()
learning_rate = 0.01

def train_one_epoch_numpy(model, dataloader, learning_rate):
    running_loss = 0.0

    for batch_images, batch_labels in dataloader:
        batch_loss = 0.0

        for i in range(len(batch_images)):
            x = batch_images[i].squeeze().numpy()
            label_int = batch_labels[i].item()

            # 2. Vrai Encodage One-Hot
            y = np.zeros(10)
            y[label_int] = 1.0

            # 3. Forward pass
            prediction = model.forward(x)

            # 4. Calcul de l'erreur (Cross-Entropy)
            loss = -np.sum(y * np.log(prediction + 1e-9))
            batch_loss += loss

            # 5. Dérivée combinée (Cross-Entropy + Softmax)
            dloss_dprob = prediction - y

            # 6. Backward pass
            dkernels, dw_fc, db_fc = model.backward(dloss_dprob)

            # --- CORRECTION : Gradient Clipping (Conservé par sécurité) ---
            dkernels = np.clip(dkernels, -1.0, 1.0)
            dw_fc = np.clip(dw_fc, -1.0, 1.0)
            db_fc = np.clip(db_fc, -1.0, 1.0)

            # 7. Mise à jour des poids manuelle
            model.conv.kernels -= learning_rate * dkernels
            model.fc.weights -= learning_rate * dw_fc
            model.fc.bias -= learning_rate * db_fc

        running_loss += batch_loss / len(batch_images)

    return running_loss / len(dataloader)


def evaluate_model_numpy(model, dataloader):
    running_loss = 0.0
    correct = 0
    total = 0

    for batch_images, batch_labels in dataloader:
        batch_loss = 0.0

        for i in range(len(batch_images)):
            x = batch_images[i].squeeze().numpy()
            label_int = batch_labels[i].item()

            # Vrai Encodage One-Hot
            y = np.zeros(10)
            y[label_int] = 1.0

            # Forward pass
            prediction = model.forward(x)

            # Loss Cross-Entropy
            loss = -np.sum(y * np.log(prediction + 1e-9))
            batch_loss += loss

            # Précision
            predicted_label = np.argmax(prediction)
            if predicted_label == label_int:
                correct += 1
            total += 1

        running_loss += batch_loss / len(batch_images)

    accuracy = 100 * correct / total
    return running_loss / len(dataloader), accuracy

# --- PRÉPARATION DE L'ÉVALUATION (IMAGES FIXES) ---
# On crée une transformation SANS Data Augmentation pour avoir une vraie note d'Accuracy
perso_test_transform = transforms.Compose([
    transforms.Grayscale(num_output_channels=1),
    transforms.Resize((28, 28)),
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

# On charge à nouveau les dossiers, mais avec cette transformation fixe
perso_test_data = datasets.ImageFolder(
    root='./dataset_perso/testset_28x28',
    transform=perso_test_transform
)
perso_test_loader = DataLoader(perso_test_data, batch_size=32, shuffle=False)


# --- CHARGEMENT DU MODÈLE EMNIST DÉJÀ ENTRAÎNÉ ---
print("Chargement du modèle EMNIST de base...")
sauvegarde = np.load("modele_emnist_base.npz")
model.conv.kernels = sauvegarde['conv_kernels']
model.fc.weights = sauvegarde['fc_weights']
model.fc.bias = sauvegarde['fc_bias']


# --- FINE-TUNING ACCÉLÉRÉ ---
print("Début du Fine-Tuning sur le dataset personnel...")

epochs_finetuning = 30
learning_rate_finetuning = learning_rate / 4 # On donne plus de force au modèle

for epoch in range(epochs_finetuning):
    # 1. On ENTRAÎNE sur perso_loader (les images qui subissent des rotations)
    train_loss = train_one_epoch_numpy(model, perso_loader, learning_rate_finetuning)
    
    # 2. On ÉVALUE sur perso_test_loader (les images parfaitement fixes)
    val_loss, val_acc = evaluate_model_numpy(model, perso_test_loader)
    
    print(f"Fine-Tuning Epoch {epoch+1}/{epochs_finetuning} | Train Loss: {train_loss:.4f} | Perso Accuracy: {val_acc:.2f}%")


# --- SAUVEGARDE FINALE ---
print("Sauvegarde des poids du modèle final...")
np.savez("modele_chiffres.npz", 
         conv_kernels=model.conv.kernels, 
         fc_weights=model.fc.weights, 
         fc_bias=model.fc.bias)
print("Modèle final sauvegardé avec succès dans 'modele_chiffres.npz' !")