# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3pAPuS0d3d1MRMM5GLySsP6VXvvJBQt
"""
import sys
import os


sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import torch
import torchvision.datasets as datasets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim
import numpy as np
from model.cnn import CNN
from torch.utils.data import Subset

# Petite fonction pour corriger l'orientation des images EMNIST (bug officiel de la lib)
# Pour les tourner de 90°
def fix_emnist(image):
    return transforms.functional.rotate(transforms.functional.hflip(image), 90)


# 1. Transformations pour l'ENTRAÎNEMENT (avec Data Augmentation)
train_transform = transforms.Compose([
    transforms.Lambda(fix_emnist), # Corrige le sens des chiffres EMNIST
    transforms.RandomRotation(degrees=10), # Légère rotation (Personne n'ecrit parfaitement droit)
    transforms.RandomAffine(degrees=0, translate=(0.1, 0.1)), # Légéro déplacement (translation)
    transforms.ToTensor(), # Convertir l'image en tenseur Mathématique
    transforms.Normalize((0.1307,), (0.3081,)) # Normalisation standard (moyenne/écart-type MNIST/EMNIST)
])

# 2. Transformations pour le TEST / EVAL (Sans pivoter ou decalager legeremment l'image
test_transform = transforms.Compose([
    transforms.Lambda(fix_emnist), # Corrige aussi le sens pour les tests
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,)) # Même normalisation obligatoire !
])


# Chargement des datasets avec les bonnes transformations
train_data = datasets.EMNIST(
    root='./data',
    split='digits',
    train=True,
    download=True, #Pour télécharger le modèle sur internet
    transform=train_transform
)

test_data = datasets.EMNIST(
    root='./data',
    split='digits',
    train=False,
    download=True,
    transform=test_transform
)


train_subset = Subset(train_data, range(5000))
test_subset = Subset(test_data, range(1000))

# DataLoader : regroupe les images par paquet de 64
# DataLoader basés sur ces sous-ensembles minuscules
train_loader = DataLoader(train_subset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_subset, batch_size=64, shuffle=False)

#train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
#test_loader = DataLoader(test_data, batch_size=64, shuffle=False)



# 3. Transformations pour les données personnelles
perso_transform = transforms.Compose([
    transforms.Grayscale(num_output_channels=1), # Forcer en Noir & Blanc
    transforms.Resize((28, 28)), # Standardiser la taille pour le modèle
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,)) # Conserver la normalisation EMNIST
])

# Chargement depuis tes 10 dossiers (0 à 9)
perso_data = datasets.ImageFolder(
    root='./dataset_perso',
    transform=perso_transform
)

# DataLoader pour le fine-tuning ou l'évaluation
perso_loader = DataLoader(perso_data, batch_size=32, shuffle=False)

# Initialisation du modèle fait maison (NumPy)
model = CNN()
learning_rate = 0.001

def train_one_epoch_numpy(model, dataloader, learning_rate):
    running_loss = 0.0

    for batch_images, batch_labels in dataloader:
        batch_loss = 0.0

        for i in range(len(batch_images)):
            # 1. Extraction et conversion en NumPy (28x28)
            x = batch_images[i].squeeze().numpy()
            label_int = batch_labels[i].item()

            # 2. Encodage One-Hot pour la Loss
            y = np.zeros(10)
            y[label_int] = 1

            # 3. Forward pass
            prediction = model.forward(x)

            # 4. Calcul de l'erreur (MSE)
            loss = np.sum((y - prediction) ** 2)
            batch_loss += loss

            # 5. Dérivée de l'erreur
            dloss_dprob = -2 * (y - prediction)

            # 6. Backward pass (Gradients)
            dkernels, dw_fc, db_fc = model.backward(dloss_dprob)

            # 7. Mise à jour des poids manuelle
            model.conv.kernels -= learning_rate * dkernels
            model.fc.weights -= learning_rate * dw_fc
            model.fc.bias -= learning_rate * db_fc

        running_loss += batch_loss / len(batch_images)

    return running_loss / len(dataloader)


def evaluate_model_numpy(model, dataloader):
    running_loss = 0.0
    correct = 0
    total = 0

    for batch_images, batch_labels in dataloader:
        batch_loss = 0.0

        for i in range(len(batch_images)):
            x = batch_images[i].squeeze().numpy()
            label_int = batch_labels[i].item()

            y = np.zeros(10)
            y[label_int] = 1

            # Forward pass uniquement
            prediction = model.forward(x)

            # Loss pour le suivi
            loss = np.sum((y - prediction) ** 2)
            batch_loss += loss

            # Précision
            predicted_label = np.argmax(prediction)
            if predicted_label == label_int:
                correct += 1
            total += 1

        running_loss += batch_loss / len(batch_images)

    accuracy = 100 * correct / total
    return running_loss / len(dataloader), accuracy


# --- BOUCLE PRINCIPALE ---
epochs = 5

print("Début de l'entraînement sur EMNIST...")
for epoch in range(epochs):
    train_loss = train_one_epoch_numpy(model, train_loader, learning_rate)
    val_loss, val_acc = evaluate_model_numpy(model, test_loader)
    print(f"Epoch {epoch+1}/{epochs} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Val Accuracy: {val_acc:.2f}%")

print("Début du Fine-Tuning sur le dataset personnel...")
for epoch in range(epochs):
    # Entraînement spécifique sur ton dataset perso
    train_loss = train_one_epoch_numpy(model, perso_loader, learning_rate)
    val_loss, val_acc = evaluate_model_numpy(model, perso_loader)
    print(f"Fine-Tuning Epoch {epoch+1}/{epochs} | Train Loss: {train_loss:.4f} | Perso Accuracy: {val_acc:.2f}%")

print("Entraînement terminé !")